/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PremiumRouteImport } from './routes/premium'
import { Route as JoinRoomRouteImport } from './routes/join-room'
import { Route as CreateRoomRouteImport } from './routes/create-room'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeamCodeRouteImport } from './routes/team.$code'
import { Route as PremiumSuccessRouteImport } from './routes/premium.success'
import { Route as PremiumCancelRouteImport } from './routes/premium.cancel'
import { Route as LobbyCodeRouteImport } from './routes/lobby.$code'
import { Route as BattleCodeRouteImport } from './routes/battle.$code'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'

const PremiumRoute = PremiumRouteImport.update({
  id: '/premium',
  path: '/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoomRoute = JoinRoomRouteImport.update({
  id: '/join-room',
  path: '/join-room',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoomRoute = CreateRoomRouteImport.update({
  id: '/create-room',
  path: '/create-room',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamCodeRoute = TeamCodeRouteImport.update({
  id: '/team/$code',
  path: '/team/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiumSuccessRoute = PremiumSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PremiumRoute,
} as any)
const PremiumCancelRoute = PremiumCancelRouteImport.update({
  id: '/cancel',
  path: '/cancel',
  getParentRoute: () => PremiumRoute,
} as any)
const LobbyCodeRoute = LobbyCodeRouteImport.update({
  id: '/lobby/$code',
  path: '/lobby/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const BattleCodeRoute = BattleCodeRouteImport.update({
  id: '/battle/$code',
  path: '/battle/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/premium': typeof PremiumRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/battle/$code': typeof BattleCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/premium/cancel': typeof PremiumCancelRoute
  '/premium/success': typeof PremiumSuccessRoute
  '/team/$code': typeof TeamCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/premium': typeof PremiumRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/battle/$code': typeof BattleCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/premium/cancel': typeof PremiumCancelRoute
  '/premium/success': typeof PremiumSuccessRoute
  '/team/$code': typeof TeamCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-room': typeof CreateRoomRoute
  '/join-room': typeof JoinRoomRoute
  '/premium': typeof PremiumRouteWithChildren
  '/auth/callback': typeof AuthCallbackRoute
  '/battle/$code': typeof BattleCodeRoute
  '/lobby/$code': typeof LobbyCodeRoute
  '/premium/cancel': typeof PremiumCancelRoute
  '/premium/success': typeof PremiumSuccessRoute
  '/team/$code': typeof TeamCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-room'
    | '/join-room'
    | '/premium'
    | '/auth/callback'
    | '/battle/$code'
    | '/lobby/$code'
    | '/premium/cancel'
    | '/premium/success'
    | '/team/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-room'
    | '/join-room'
    | '/premium'
    | '/auth/callback'
    | '/battle/$code'
    | '/lobby/$code'
    | '/premium/cancel'
    | '/premium/success'
    | '/team/$code'
  id:
    | '__root__'
    | '/'
    | '/create-room'
    | '/join-room'
    | '/premium'
    | '/auth/callback'
    | '/battle/$code'
    | '/lobby/$code'
    | '/premium/cancel'
    | '/premium/success'
    | '/team/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateRoomRoute: typeof CreateRoomRoute
  JoinRoomRoute: typeof JoinRoomRoute
  PremiumRoute: typeof PremiumRouteWithChildren
  AuthCallbackRoute: typeof AuthCallbackRoute
  BattleCodeRoute: typeof BattleCodeRoute
  LobbyCodeRoute: typeof LobbyCodeRoute
  TeamCodeRoute: typeof TeamCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/premium': {
      id: '/premium'
      path: '/premium'
      fullPath: '/premium'
      preLoaderRoute: typeof PremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-room': {
      id: '/join-room'
      path: '/join-room'
      fullPath: '/join-room'
      preLoaderRoute: typeof JoinRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-room': {
      id: '/create-room'
      path: '/create-room'
      fullPath: '/create-room'
      preLoaderRoute: typeof CreateRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/$code': {
      id: '/team/$code'
      path: '/team/$code'
      fullPath: '/team/$code'
      preLoaderRoute: typeof TeamCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premium/success': {
      id: '/premium/success'
      path: '/success'
      fullPath: '/premium/success'
      preLoaderRoute: typeof PremiumSuccessRouteImport
      parentRoute: typeof PremiumRoute
    }
    '/premium/cancel': {
      id: '/premium/cancel'
      path: '/cancel'
      fullPath: '/premium/cancel'
      preLoaderRoute: typeof PremiumCancelRouteImport
      parentRoute: typeof PremiumRoute
    }
    '/lobby/$code': {
      id: '/lobby/$code'
      path: '/lobby/$code'
      fullPath: '/lobby/$code'
      preLoaderRoute: typeof LobbyCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/battle/$code': {
      id: '/battle/$code'
      path: '/battle/$code'
      fullPath: '/battle/$code'
      preLoaderRoute: typeof BattleCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PremiumRouteChildren {
  PremiumCancelRoute: typeof PremiumCancelRoute
  PremiumSuccessRoute: typeof PremiumSuccessRoute
}

const PremiumRouteChildren: PremiumRouteChildren = {
  PremiumCancelRoute: PremiumCancelRoute,
  PremiumSuccessRoute: PremiumSuccessRoute,
}

const PremiumRouteWithChildren =
  PremiumRoute._addFileChildren(PremiumRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateRoomRoute: CreateRoomRoute,
  JoinRoomRoute: JoinRoomRoute,
  PremiumRoute: PremiumRouteWithChildren,
  AuthCallbackRoute: AuthCallbackRoute,
  BattleCodeRoute: BattleCodeRoute,
  LobbyCodeRoute: LobbyCodeRoute,
  TeamCodeRoute: TeamCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
